# Generated by Django 5.0.6 on 2024-06-26 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="user_photos/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="short_bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                choices=[
                    ("IN", "India"),
                    ("US", "United States"),
                    ("UK", "United Kingdom"),
                    ("AU", "Australia"),
                    ("CA", "Canada"),
                    ("NZ", "New Zealand"),
                    ("AF", "Afghanistan"),
                ],
                default="IN",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=15)),
                ("address_line_1", models.TextField(max_length=250)),
                ("address_line_2", models.TextField(max_length=250)),
                ("address_line_3", models.TextField(max_length=250)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("IN", "India"),
                            ("US", "United States"),
                            ("UK", "United Kingdom"),
                            ("AU", "Australia"),
                            ("CA", "Canada"),
                            ("NZ", "New Zealand"),
                            ("AF", "Afghanistan"),
                        ],
                        default="IN",
                        max_length=50,
                    ),
                ),
                ("pincode", models.CharField(max_length=25)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("is_default", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
    ]
