# Generated by Django 5.0.6 on 2024-06-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_customuser_profile_photo_customuser_short_bio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="job_title",
        ),
        migrations.AddField(
            model_name="customuser",
            name="drinking_habit",
            field=models.CharField(
                choices=[
                    ("no", "No"),
                    ("occasionally", "Occasionally"),
                    ("socially", "Socially"),
                    ("regularly", "Regularly"),
                    ("heavily", "Heavily"),
                ],
                default="no",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="qualification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("High School", "High School"),
                    ("Bachelor's Degree", "Bachelor's Degree"),
                    ("Master's Degree", "Master's Degree"),
                    ("Doctorate", "Doctorate"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="short_reel",
            field=models.FileField(blank=True, null=True, upload_to="short_reel/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="smoking_habit",
            field=models.CharField(
                choices=[
                    ("no", "No"),
                    ("occasionally", "Occasionally"),
                    ("regularly", "Regularly"),
                ],
                default="no",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="hobby",
            field=models.ManyToManyField(blank=True, null=True, to="user.hobby"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="interest",
            field=models.ManyToManyField(blank=True, null=True, to="user.interest"),
        ),
    ]
