# Generated by Django 5.0.6 on 2024-06-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_hobby_interest_remove_customuser_job_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
