# Generated by Django 5.0.6 on 2024-06-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="hobby",
            field=models.ManyToManyField(to="user.hobby"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="interest",
            field=models.ManyToManyField(to="user.interest"),
        ),
    ]
