# Generated by Django 5.0.6 on 2024-06-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_customuser_hobby_alter_customuser_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="job_title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
