# Generated by Django 5.0.6 on 2024-06-30 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_customuser_job_title_alter_address_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                choices=[
                    ("India", "India"),
                    ("United States", "United States"),
                    ("United Kingdom", "United Kingdom"),
                    ("Australia", "Australia"),
                    ("Canada", "Canada"),
                    ("New Zealand", "New Zealand"),
                    ("Afghanistan", "Afghanistan"),
                ],
                default="India",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                choices=[
                    ("India", "India"),
                    ("United States", "United States"),
                    ("United Kingdom", "United Kingdom"),
                    ("Australia", "Australia"),
                    ("Canada", "Canada"),
                    ("New Zealand", "New Zealand"),
                    ("Afghanistan", "Afghanistan"),
                ],
                default="India",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="drinking_habit",
            field=models.CharField(
                choices=[
                    ("Non-drinker", "Non-drinker"),
                    ("Occasional drinker", "Occasional drinker"),
                    ("Social drinker", "Social drinker"),
                    ("Regular drinker", "Regular drinker"),
                    ("Heavy drinker", "Heavy drinker"),
                    ("Trying to quit", "Trying to quit"),
                ],
                default="no",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="smoking_habit",
            field=models.CharField(
                choices=[
                    ("Non-smoker", "Non-smoker"),
                    ("Occasional smoker", "Occasional smoker"),
                    ("Regular smoker", "Regular smoker"),
                    ("Heavy smoker", "Heavy smoker"),
                    ("Trying to quit", "Trying to quit"),
                ],
                default="no",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=100)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("10th", "10th"),
                            ("12th", "12th"),
                            ("diploma", "Diploma"),
                            ("associate", "Associate"),
                            ("bachelor", "Bachelor's"),
                            ("master", "Master's"),
                            ("doctorate", "Doctorate"),
                        ],
                        max_length=25,
                    ),
                ),
                ("field_of_study", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.skill"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
