# Generated by Django 5.0.6 on 2024-06-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_skill_alter_address_country_alter_customuser_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
